### ISSUE TITLE
Should default timing mode be linear?

### ISSUE THREAD

**Issue by reececomo** [srpatel/pixi-actions#10]
We were trying to track down an obscure visual issue with two actions running at once, and I did not realise the libraries default timing mode is the custom `pow2out` timing. It's written pretty clearly in the README, but my brain just assumed the default timing mode would be linear.

Do wethink a better default might be `linear`? I know that's what SKActions and most other tweening libraries use.

Also side-note: It might be worth just bundling the "standard" timing functions from here: https://raw.githubusercontent.com/ai/easings.net/master/src/easings/easingsFunctions.ts

**Comment by reececomo** [comment]
For reference, we have now set:

```ts
Action.DefaultTimingMode = Easings.linear;
```

👍 just throwing it out there that maybe it would be a good default

**Comment by srpatel** [comment]
Being able to set the default is a good idea. `pow2out` is the default because it's the one I personally use (almost exclusively).

**Comment by reececomo** [comment]
Fair enough, will leave that thought with you 🙉
