### ISSUE TITLE
Add `paused`?

### ISSUE THREAD

**Issue by reececomo** [srpatel/pixi-actions#6]
Great work, love the library. Would be great to have a built-in way to pause `.tick()` for specific entities 👍 to mirror [SKNode.paused](https://developer.apple.com/documentation/spritekit/sknode/1483113-paused)

**Comment by srpatel** [comment]
I'm glad you like the library!

Actions themselves already have a `pause()` method, which may be sufficient:

    const a = Actions.moveTo(node, 0, 0, 0.2).play();
    a.pause();
    a.play();

I'm not sure it makes sense to pause the node itself, since not all Actions have a target. Namely, `runFunc`, `parallel`, `sequence`, `repeat` and `delay`.

There is a `TargetedAction` class though, so it would be possible to specifically pause Actions targeting a specific node if this is really needed.

**Comment by reececomo** [comment]
Yeah in an ideal world I guess targeted actions would skip when a node or an ancestor up the tree is paused?

I believe this is roughly what Apple does with `SKNode.paused`.

e.g. [Actions.ts#150](https://github.com/srpatel/pixi-actions/blob/fbe0eba9b976e4833a57b31b4bea871871f85299/src/Actions.ts#L150):
 
```ts
if (action instanceof TargetedAction) {
  // If the target is paused, skip update.
  if (isTargetPaused(action.target)) continue;
```

And a function to perform a recursive check:

```ts
function isTargetPaused(target: any): boolean {
  let next: any = target;
  while (next !== undefined) {
    if (next.pausedActions === true) return true;
    next = next.parent;
  }
  return false;
}
```

You could probably do it prettier with an interface/typeguard?

**Comment by reececomo** [comment]
For our use case we have two main view hierarchies - `menu` and `gameWorld`. As a temporary workaround we've just been avoiding using `Actions` to animate anything in the `menu`, and then we pause `Actions.tick()` in the renderer:

```ts
if (!this.gameScene.isPaused) {
  // When NOT paused, let animations play.
  Actions.tick(dt);
}
```

**Comment by reececomo** [comment]
I think the main complication here is that in SpriteKit, all `SKAction` (including `.sequence()` and `.group()`) are always run against a target.

If you'd prefer to keep your interfaces exactly as they are now, we might just need to make a fork instead 😄

```ts
Actions.sequence(target, [myAction1, myAction2, ... ]).play();
```
