### ISSUE TITLE
Will Pixi 8 be supported? Are any changes necessary?

### ISSUE THREAD

**Issue by Nantris** [srpatel/pixi-actions#7]
Very cool library, thank you for sharing! I'd love to use it, but I don't want to lock myself in to Pixi v7. Is that a valid concern?

Thank you for your great work!

**Comment by srpatel** [comment]
The library already works with Pixi v8, except there is a slight change in the `Ticker` API, so `pixi-actions` must be registered as follows:

```javascript
app.ticker.add((tick) => Actions.tick(tick.deltaTime/60));
```

Once Pixi v8 is out of Beta, and the API fixed, I can update the documentation (and the peerDependency) to support both versions.

In short, no need to worry about being locked into Pixi v7!

**Comment by Nantris** [comment]
Thanks so much for the great library and for taking the time to reply, I really appreciate it a lot!
